### ISSUE TITLE
macos version difficult to use

### ISSUE THREAD

**Issue by utdrmac** [br0xen/boltbrowser#25] opened 2018-04-26 05:04 UTC
Very difficult to use/see. Lots of garbled characters on screen. Using latest iTerm2/UTF8/xterm.

<img width="1282" alt="screen shot 2018-04-26 at 12 03 13 am" src="https://user-images.githubusercontent.com/4413670/39286766-5358876e-48e5-11e8-9ddf-49006b308353.png">

**Comment by br0xen** [comment] 2018-04-26 12:18
I'll have to try to track down a mac to test this on. It may be your terminal config, though. I've seen issues similar to this before where terminal configuration fixes it (not saying that's the issue for sure, but it's possible.)

**Comment by utdrmac** [comment] 2018-04-27 03:46
What settings should I use? What terminal type/etc?

**Comment by br0xen** [comment] 2018-04-27 13:06
I was able to test it on a mac in the default terminal app and it worked fine. Have you tried it with any other settings? I apologize, I just don't have easy access to that setup so I don't really know the direction to point you in. I'm asking around to some friends that are more familiar with Mac that may be able to help.

**Comment by br0xen** [comment] 2018-10-24 12:45
I apologize, but I'm not sure what else to do about this issue. As I mentioned, I don't have easy access to a mac, but everyone that I have had do testing on a mac hasn't been able to reproduce it... I'm going to close the issue, if others start showing up with the same problem we can revisit it.

**Closed by br0xen** 2018-10-24 12:45 UTC

**Comment by utdrmac** [comment] 2018-10-24 13:32
No worries. It's been working fine for me when I use `export TERM=xterm-256color`. Since that is not my default TERM, it would have been nice to see a requirement or a warning printed that says "you need to use xterm-256color" or just have the app set that for me on startup if detected otherwise.

**Comment by br0xen** [comment] 2018-10-24 13:51
Oh, interesting... Good to know, maybe I'll put something in the readme
about that.
It looks like people experience other issues with the termbox library
depending on their Terminal/TERM combination. :P

Thanks!
